[package]
name = "retint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arr_macro = "0.2.1"
crossterm = "0.26.1"
memory-stats = "1.1.0"
nalgebra = "0.32.2"
rand = "0.8.5"
